### PR TITLE
Xcode 10 support on macOS

### PR DESCRIPTION
**Pull request by dcaravana**

### CODE REVIEW

**Comment by XadillaX** [comment]
Well done!

Would you please add a test environment about your changes in `.travis.yml`? Thx

**Comment by XadillaX** [comment]
BTW, I can `install` this package under macOS. What is this PR mainly for?

```
$ npm install mp4duration

✔ Installed 1 packages
  CXX(target) Release/obj.target/mp4duration/src/mp4duration.o
  CXX(target) Release/obj.target/mp4duration/src/parse.o
  SOLINK_MODULE(target) Release/mp4duration.node
✔ Run 1 scripts
✔ All packages installed (2 packages installed from npm registry, used 5s(network 1s), speed 370.93kB/s, json 2(4.89kB), tarball 378.29kB)
```

**Comment by dcaravana** [comment]
This is a fix for Xcode 10, see https://github.com/nodejs/node-gyp/issues/469.

Is Xcode 10 installed on your Mac? That would explain why you managed to install the module.

I'll add the environment next.

**Comment by dcaravana** [comment]
Finally managed to configure Travis... Apologies for the many tries but I got confused by the many sources of discording fixes and the non-linear support for env matrix.
Still not perfect but it's testing what we need to test.

**Comment by XadillaX** [comment]
1.0.0 released.

**Pull request merged**
